version: "3.8"

services:
  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    environment:
      CHROMA_DB_TYPE: postgres
      CHROMA_DB_CONNECTION_URI: postgresql://postgres:password@db/chromadb
    depends_on:
      - db
    restart: always
  db:
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chromadb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  es:
    image: elasticsearch:8.16.1
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_USERNAME: "elastic"
      ELASTIC_PASSWORD: "MyPw123"
      discovery.type: single-node
    volumes:
      - ./configs/elasticsearch/config.yml:/usr/share/elasticsearch/docker/config/elasticsearch.yml:ro
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

volumes:
  db-data:
  es-data: